# Generated by Django 3.1.6 on 2021-09-20 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='CartOrder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CartOrder', to='Account.cart'),
        ),
    ]
