# Generated by Django 3.1.6 on 2021-09-13 10:28

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('image', models.ImageField(upload_to='CategoryImage/')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=155)),
                ('Image', models.ImageField(upload_to='ProductImages/')),
                ('Slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='Name')),
                ('Description', models.TextField(max_length=250)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='Product.category')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
    ]
