# Generated by Django 3.1.6 on 2021-09-13 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='slug',
            new_name='Slug',
        ),
    ]
