# Generated by Django 3.1.6 on 2021-09-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_auto_20210913_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='AddToTop',
            field=models.BooleanField(default=False),
        ),
    ]
