# Generated by Django 3.1.6 on 2021-09-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_category_addtotop'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='AddToListCategory',
            field=models.BooleanField(default=True),
        ),
    ]
